- name: Deploy a mysql DB
  hosts: db_servers
  roles:
    - python
    - mysql_db

- name: Deploy a web app
  hosts: web_servers
  roles:
    - python
    - flask
    - app

- name: Create and configure load load_balancer_arn
  hosts: localhost
  connection: local
  roles:
    - load_balancer
